version: '3'
services:
  winery:
    image: opentosca/winery:latest
    environment:
      WINERY_HOSTNAME: ${PUBLIC_HOSTNAME}
      WORKFLOWMODELER_HOSTNAME: ${PUBLIC_HOSTNAME}
      TOPOLOGYMODELER_HOSTNAME: ${PUBLIC_HOSTNAME}
      CONTAINER_HOSTNAME: ${PUBLIC_HOSTNAME}
      WINERY_REPOSITORY_PROVIDER: 'yaml'
      WINERY_REPOSITORY_URL: 'https://github.com/radon-h2020/radon-particles'
    ports:
      - '8080:8080'
