apiVersion: 1.0.0
metadata:
  name: radon-workspace
  # generateName: radon-workspace-
projects:
  - name: radon-particles
    source:
      type: git
      location: https://github.com/radon-h2020/radon-particles
components:
  - alias: theia-editor
    type: cheEditor
    id: eclipse/che-theia/next
  - alias: radon-gmt
    type: kubernetes
    mountSources: true
    reference: https://raw.githubusercontent.com/OpenTOSCA/winery/project/radon/deploy/che/winery.yaml
